In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('data/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [6]:
df=df.dropna()

In [7]:
df.drop(columns=['customerID'],axis=1,inplace=True)

In [8]:
X=df.drop(columns=['Churn'],axis=1)
y=df['Churn']

In [9]:
X.shape

(7032, 19)

In [10]:
num_faeture=X.select_dtypes(exclude='object').columns
cat_feature=X.select_dtypes(include="object").columns

In [11]:
num_faeture

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='object')

In [12]:
cat_feature

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

In [13]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

numerical_feature=StandardScaler()
categorical_feature=OneHotEncoder(drop='first')


preprocessor=ColumnTransformer(
    [
        ('onehotencoder',categorical_feature,cat_feature),
        ('StandardScaler',numerical_feature,num_faeture)
    ],remainder='passthrough'
)

In [14]:
X=preprocessor.fit_transform(X)

In [15]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,-0.440327,-1.280248,-1.161694,-0.994194
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,-0.440327,0.064303,-0.260878,-0.173740
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,-0.440327,-1.239504,-0.363923,-0.959649
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,-0.440327,0.512486,-0.747850,-0.195248
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,-0.440327,-1.239504,0.196178,-0.940457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,-0.440327,-0.343137,0.664868,-0.129180
7028,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,-0.440327,1.612573,1.276493,2.241056
7029,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,-0.440327,-0.872808,-1.170004,-0.854514
7030,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,2.271039,-1.158016,0.319168,-0.872095
7031,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,-0.440327,1.368109,1.357932,2.012344

In [16]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [17]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score

In [18]:
def evaluate(true,pred):
    AccuracyScore=accuracy_score(true,pred)
    f1Score=f1_score(true,pred,pos_label='Yes')
    precisionScore=precision_score(true,pred,pos_label='Yes')
    recallScore=recall_score(true,pred,pos_label='Yes')
    
    return AccuracyScore,f1Score,precisionScore,recallScore

In [19]:
import warnings
warnings.filterwarnings('ignore')

In [20]:
models={
    "RandomForestClassifier":RandomForestClassifier(),
    "GradientBoostingClassifier":GradientBoostingClassifier(),
    "DecisionTreeClassifier":DecisionTreeClassifier(),
    'LogisticRegression':LogisticRegression(),
    "KNeighborsClassifier":KNeighborsClassifier(),
    "SVC":SVC()
}
model_list=[]

for i in range(len(models)):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    
    y_train_acc,y_train_f1,y_train_precision,y_train_recall=evaluate(y_train,y_train_pred)
    y_test_acc,y_test_f1,y_test_precision,y_test_recall=evaluate(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('-------------------------------')
    
    print("Train performance")
    print('accracy score:{:.4f}'.format(y_train_acc))
    print('f1 score:{:.4f}'.format(y_train_f1))
    print('precision score :{:.4f}'.format(y_train_precision))
    print('recall score :{:.4f}'.format(y_train_recall))
    
    print('\n')
    
    print("Test performance")
    print('accracy score:{:.4f}'.format(y_test_acc))
    print('f1 score:{:.4f}'.format(y_test_f1))
    print('precision score :{:.4f}'.format(y_test_precision))
    print('recall score :{:.4f}'.format(y_test_recall))

RandomForestClassifier
-------------------------------
Train performance
accracy score:0.9983
f1 score:0.9968
precision score :0.9965
recall score :0.9972


Test performance
accracy score:0.7850
f1 score:0.5322
precision score :0.6143
recall score :0.4694
GradientBoostingClassifier
-------------------------------
Train performance
accracy score:0.8280
f1 score:0.6478
precision score :0.7165
recall score :0.5911


Test performance
accracy score:0.7918
f1 score:0.5537
precision score :0.6271
recall score :0.4956
DecisionTreeClassifier
-------------------------------
Train performance
accracy score:0.9983
f1 score:0.9968
precision score :0.9993
recall score :0.9943


Test performance
accracy score:0.7150
f1 score:0.4653
precision score :0.4551
recall score :0.4760
LogisticRegression
-------------------------------
Train performance
accracy score:0.8072
f1 score:0.6111
precision score :0.6636
recall score :0.5663


Test performance
accracy score:0.7895
f1 score:0.5606
precision score :0.6146
recall score :0.5153
KNeighborsClassifier
-------------------------------
Train performance
accracy score:0.8417
f1 score:0.6947
precision score :0.7175
recall score :0.6733


Test performance
accracy score:0.7548
f1 score:0.5195
precision score :0.5308
recall score :0.5087
SVC
-------------------------------
Train performance
accracy score:0.8161
f1 score:0.6092
precision score :0.7059
recall score :0.5358


Test performance
accracy score:0.7952
f1 score:0.5420
precision score :0.6494
recall score :0.4651